name: Job Ingestion Cron

on:
  schedule:
    - cron: "0 * * * *" # every 1 hour
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger FastAPI ingestion
        run: |
          curl -X POST https://jobs-parser.onrender.com/ingest
