name: Job Ingestion Cron

on:
  schedule:
    - cron: "0 * * * *" # every 1 hour
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Call FastAPI ingest endpoint
        run: |
          curl -X POST https://YOUR-BACKEND-URL.onrender.com/ingest
